"""
agent/setup_wizard.py — First-run setup for new Oblivion users.

Shown automatically when ~/.oblivion/config.env doesn't exist.
Walks the user through:
  1. Picking an LLM provider (Gemini recommended — free + fast)
  2. Pasting their API key
  3. Optional: enabling voice
  4. Writing config.env to disk

Also runs the legacy migration from ~/.ai-agent/ → ~/.oblivion/.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from agent.paths import (
    config_env, oblivion_home, oblivion_cache,
    migrate_from_legacy, is_first_run, describe,
)


BANNER = r"""
 ██████╗ ██████╗ ██╗     ██╗██╗   ██╗██╗ ██████╗ ███╗   ██╗
██╔═══██╗██╔══██╗██║     ██║██║   ██║██║██╔═══██╗████╗  ██║
██║   ██║██████╔╝██║     ██║██║   ██║██║██║   ██║██╔██╗ ██║
██║   ██║██╔══██╗██║     ██║╚██╗ ██╔╝██║██║   ██║██║╚██╗██║
╚██████╔╝██████╔╝███████╗██║ ╚████╔╝ ██║╚██████╔╝██║ ╚████║
 ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
"""

# Providers we offer in the wizard
PROVIDERS = [
    {
        "key": "1",
        "name": "Gemini 2.5 Flash",
        "tag": "RECOMMENDED",
        "details": "1M context, blazing fast, free 1500 req/day",
        "env_key": "GEMINI_API_KEY",
        "default_model": "gemini/gemini-2.5-flash",
        "signup_url": "https://aistudio.google.com/apikey",
    },
    {
        "key": "2",
        "name": "Groq Llama 3.3 70B",
        "tag": "FAST",
        "details": "200+ tokens/sec, free tier (12k tok/min)",
        "env_key": "GROQ_API_KEY",
        "default_model": "groq/llama-3.3-70b-versatile",
        "signup_url": "https://console.groq.com/keys",
    },
    {
        "key": "3",
        "name": "Anthropic Claude Sonnet 4",
        "tag": "PREMIUM",
        "details": "Genius-level reasoning, paid ($3/$15 per 1M)",
        "env_key": "ANTHROPIC_API_KEY",
        "default_model": "anthropic/claude-sonnet-4-20250514",
        "signup_url": "https://console.anthropic.com",
    },
    {
        "key": "4",
        "name": "Ollama (local)",
        "tag": "OFFLINE",
        "details": "Run models locally, no API key needed",
        "env_key": None,
        "default_model": "ollama/qwen3-coder:480b-cloud",
        "signup_url": "https://ollama.com/download",
    },
]


def _color(text: str, code: str) -> str:
    """ANSI color wrapper — degrades to plain text if NO_COLOR is set."""
    if os.getenv("NO_COLOR") or not sys.stdout.isatty():
        return text
    return f"\033[{code}m{text}\033[0m"


def _green(t):   return _color(t, "1;32")
def _cyan(t):    return _color(t, "1;36")
def _yellow(t):  return _color(t, "1;33")
def _magenta(t): return _color(t, "1;35")
def _dim(t):     return _color(t, "2")
def _bold(t):    return _color(t, "1")


def _input(prompt: str, default: str = "") -> str:
    """Robust input with EOF/keyboard-interrupt handling."""
    try:
        suffix = f" [{default}]" if default else ""
        val = input(prompt + suffix + ": ").strip()
        return val or default
    except (EOFError, KeyboardInterrupt):
        print("\n\nSetup cancelled. Run `oblivion` again to retry.")
        sys.exit(1)


def _write_config(values: dict) -> None:
    """Persist config to ~/.oblivion/config.env."""
    path = config_env()
    lines = ["# Oblivion config — generated by setup wizard", ""]
    for key, val in values.items():
        if val:
            lines.append(f"{key}={val}")
    path.write_text("\n".join(lines) + "\n")


def run_wizard() -> bool:
    """Run the interactive first-time setup. Returns True if config was written."""
    print(_cyan(BANNER))
    print(_dim("                  First-time setup\n"))
    print(_bold("Welcome to Oblivion!") + " Let's get you set up in 60 seconds.")
    print()

    # ── Migration first (silent if nothing to migrate) ─────────────────────
    moved = migrate_from_legacy()
    if moved:
        print(_yellow("↻ Migrated legacy data from ~/.ai-agent/ → ~/.oblivion/:"))
        for k in moved:
            print(_dim(f"   • {k}"))
        print()
        # If we migrated a config, we're done — no wizard needed
        if "config.env" in moved:
            print(_green("✓ Your previous configuration was imported."))
            print(_dim(f"   Edit it anytime: {config_env()}"))
            print()
            return True

    # ── Step 1: Choose provider ────────────────────────────────────────────
    print(_bold("Step 1/3: Pick your LLM provider"))
    print()
    for p in PROVIDERS:
        tag = _magenta(f"[{p['tag']}]")
        print(f"  {_cyan(p['key'])}. {_bold(p['name']):28s} {tag}")
        print(f"     {_dim(p['details'])}")
    print()
    choice = _input("Choose 1-4", "1")

    provider = next((p for p in PROVIDERS if p["key"] == choice), PROVIDERS[0])
    print()
    print(_green(f"✓ Selected: {provider['name']}"))
    print()

    # ── Step 2: API key (if needed) ────────────────────────────────────────
    config = {
        "DEFAULT_MODEL": provider["default_model"],
        "WORKSPACE_DIR": str(Path.cwd()),
        "MAX_ITERATIONS": "40",
        "MAX_TOKENS": "1500",
        "TEMPERATURE": "0.05",
        "REQUIRE_APPROVAL_FOR_WRITE": "true",
        "REQUIRE_APPROVAL_FOR_BASH": "true",
        "FRIDAY_ENABLED": "true",
        "FRIDAY_NAME": "boss",
        "FRIDAY_VOICE": "aria",
        "OBLIVION_PRELOAD_VOICE": "1",
        "PARALLEL_EMBEDDINGS": "8",
        "EMBED_MODEL": "all-minilm",
        "LITELLM_LOCAL_MODEL_COST_MAP": "True",
    }

    if provider["env_key"]:
        print(_bold(f"Step 2/3: Paste your {provider['name']} API key"))
        print(_dim(f"   Get one free: {provider['signup_url']}"))
        print()
        key = _input(f"{provider['env_key']}").strip()
        while not key:
            print(_yellow("⚠ API key required to continue. Press Ctrl+C to abort."))
            key = _input(f"{provider['env_key']}").strip()
        config[provider["env_key"]] = key
        print(_green("✓ Key saved"))
        print()
    else:
        print(_bold("Step 2/3: Ollama setup"))
        print(_dim(f"   Install Ollama: {provider['signup_url']}"))
        print(_dim("   Then run: ollama pull qwen2.5-coder:7b"))
        print()
        _input("Press Enter when Ollama is running locally")
        print()

    # ── Step 3: Voice (optional) ───────────────────────────────────────────
    print(_bold("Step 3/3: Enable voice? (optional)"))
    print(_dim("   Press-to-talk with Ctrl+T. Adds ~1.5GB Whisper model on first use."))
    print(_dim("   You can also enable later with /meera on"))
    print()
    voice = _input("Enable voice? (y/n)", "y").lower()
    if voice in ("n", "no"):
        config["FRIDAY_ENABLED"] = "false"
        config["OBLIVION_PRELOAD_VOICE"] = "0"
        print(_dim("✓ Voice disabled. Re-enable anytime with /meera on"))
    else:
        print(_green("✓ Voice enabled"))
    print()

    # ── Optional: ElevenLabs ───────────────────────────────────────────────
    print(_bold("Bonus: ElevenLabs premium voice? (optional, free 10k chars/month)"))
    print(_dim("   Get a key: https://elevenlabs.io  — or press Enter to skip"))
    el_key = _input("ELEVENLABS_API_KEY (leave empty to skip)", "").strip()
    if el_key:
        config["ELEVENLABS_API_KEY"] = el_key
        config["FRIDAY_PROVIDER"] = "auto"
        config["FRIDAY_ELEVENLABS_VOICE"] = "rachel"
        print(_green("✓ Premium voice enabled"))
    print()

    # ── Write config ───────────────────────────────────────────────────────
    _write_config(config)
    print(_green("━" * 60))
    print(_green(f"✓ Setup complete!"))
    print(_dim(f"   Config saved to: {config_env()}"))
    print(_dim(f"   Edit anytime to change settings."))
    print(_green("━" * 60))
    print()
    print(_bold("Launching Oblivion..."))
    print()
    return True


def maybe_run() -> None:
    """Called from main(). Runs wizard if first-time, else just loads config."""
    from agent.paths import load_config_env

    if is_first_run():
        run_wizard()

    # Always load config into env (whether from wizard or pre-existing)
    load_config_env()


if __name__ == "__main__":
    run_wizard()
