"""
tools/planner.py — Task decomposition tool

When user says 'build me a React app', the agent should NOT try to do everything
in one ReAct loop. Instead it should:

1. Call plan_task(goal) to break it into atomic file-level steps
2. Show the plan to the user for approval
3. Execute one step at a time with checkpointing
"""
from __future__ import annotations
import json
from typing import Optional


def plan_task(goal: str, max_files: int = 10) -> str:
    """Break a multi-file task into atomic file-level steps.

    Returns a structured plan as text. The agent should display this to user
    BEFORE writing any code, and wait for confirmation.

    Args:
        goal: The user's high-level request (e.g. "build a React landing page")
        max_files: Cap on number of files (prevents runaway projects)

    Returns:
        Formatted plan string with numbered steps.
    """
    # The plan is generated by the LLM in the agent loop, not by this tool.
    # This tool just enforces structure. The agent must respond to this call
    # with a structured plan in the OBSERVATION feedback.

    return f"""PLANNER ACTIVATED — decompose this goal into atomic file-level steps:

GOAL: {goal}

Respond with a numbered plan in EXACTLY this format:

PLAN:
1. <filename> — <one-line description of what this file does>
2. <filename> — <description>
3. ...

RULES:
- Each step = exactly ONE file (no batching)
- Order matters: dependencies first (e.g. package.json before src/main.tsx)
- Max {max_files} files in plan
- After listing the plan, ask user: "Approve this plan? Reply yes/no or suggest changes"
- Do NOT write any code yet. ONLY the plan.

After user approves, execute steps ONE AT A TIME — one write_file per turn, then ask
"next?" before continuing to the next step.
"""
